apiVersion: apps/v1
kind: Deployment
metadata:
  name: plant-proxy
  namespace: condition-based-serving
  labels:
    app: plant-proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: plant-proxy
  template:
    metadata:
      labels:
        app: plant-proxy
      annotations:
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/proxyCPU: "128m"
        sidecar.istio.io/proxyMemory: "128Mi"
        proxy.istio.io/config: "{'concurrency':'8'}"
    spec:
      containers:
        - name: plant-proxy
          image: shibui/ml-system-in-actions:condition_based_pattern_proxy_0.0.1
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "9000"
            - name: REST
              value: plant.condition-based-serving.svc.cluster.local:9501
            - name: GRPC
              value: plant.condition-based-serving.svc.cluster.local:9500
            - name: MODEL_SPEC_NAME
              value: plant
            - name: SIGNATURE_NAME
              value: serving_default
            - name: LABEL_PATH
              value: ./data/plant_labels.json
            - name: SAMPLE_IMAGE_PATH
              value: ./data/iris.jpg
            - name: WORKERS
              value: "2"
          ports:
            - containerPort: 9000
          resources:
            limits:
              cpu: 800m
              memory: "500Mi"
            requests:
              cpu: 800m
              memory: "500Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: plant-proxy
  namespace: condition-based-serving
  labels:
    app: plant-proxy
spec:
  ports:
    - name: rest
      port: 9000
      protocol: TCP
  selector:
    app: plant-proxy

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: plant-proxy
  namespace: condition-based-serving
  labels:
    app: plant-proxy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: plant-proxy
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
