stages:
  prepare_data:
    cmd:
      docker run --rm --name prepare_data -v /Users/shibuiyuusuke/ml-system-in-action/training_patterns/src/iris_pipeline/models:/training_patterns/src/iris_pipeline/models
      -v /Users/shibuiyuusuke/ml-system-in-action/training_patterns/src/iris_pipeline/data:/training_patterns/src/iris_pipeline/data
      -v /Users/shibuiyuusuke/ml-system-in-action/training_patterns/src/iris_pipeline/data/prepared:/training_patterns/src/iris_pipeline/data/prepared
      -v /Users/shibuiyuusuke/ml-system-in-action/training_patterns/src/iris_pipeline/data/trained:/training_patterns/src/iris_pipeline/data/trained
      -v /Users/shibuiyuusuke/ml-system-in-action/training_patterns/src/iris_pipeline/data/evaluated:/training_patterns/src/iris_pipeline/data/evaluated
      training_patterns_train_iris_pipeline:latest python iris_prepare_data.py
    deps:
      - ./data/iris_data.csv
      - ./data/iris_label.csv
      - ./iris_prepare_data.py
    params:
      - prepare.test_rate
    outs:
      - ./data/prepared
  train:
    cmd:
      docker run --rm --name train -v /Users/shibuiyuusuke/ml-system-in-action/training_patterns/src/iris_pipeline/models:/training_patterns/src/iris_pipeline/models
      -v /Users/shibuiyuusuke/ml-system-in-action/training_patterns/src/iris_pipeline/data:/training_patterns/src/iris_pipeline/data
      -v /Users/shibuiyuusuke/ml-system-in-action/training_patterns/src/iris_pipeline/data/prepared:/training_patterns/src/iris_pipeline/data/prepared
      -v /Users/shibuiyuusuke/ml-system-in-action/training_patterns/src/iris_pipeline/data/trained:/training_patterns/src/iris_pipeline/data/trained
      -v /Users/shibuiyuusuke/ml-system-in-action/training_patterns/src/iris_pipeline/data/evaluated:/training_patterns/src/iris_pipeline/data/evaluated
      training_patterns_train_iris_pipeline:latest python iris_train.py
    deps:
      - ./data/iris_label.csv
      - ./data/prepared/x_train.npy
      - ./data/prepared/y_train.npy
    params:
      - train.ml_model
      - train.save_format
      - train.save_model_name
    outs:
      - ./data/trained
  evaluate:
    cmd:
      docker run --rm --name evaluate -v /Users/shibuiyuusuke/ml-system-in-action/training_patterns/src/iris_pipeline/models:/training_patterns/src/iris_pipeline/models
      -v /Users/shibuiyuusuke/ml-system-in-action/training_patterns/src/iris_pipeline/data:/training_patterns/src/iris_pipeline/data
      -v /Users/shibuiyuusuke/ml-system-in-action/training_patterns/src/iris_pipeline/data/prepared:/training_patterns/src/iris_pipeline/data/prepared
      -v /Users/shibuiyuusuke/ml-system-in-action/training_patterns/src/iris_pipeline/data/trained:/training_patterns/src/iris_pipeline/data/trained
      -v /Users/shibuiyuusuke/ml-system-in-action/training_patterns/src/iris_pipeline/data/evaluated:/training_patterns/src/iris_pipeline/data/evaluated
      training_patterns_train_iris_pipeline:latest python iris_evaluate.py
    deps:
      - ./data/prepared/x_test.npy
      - ./data/prepared/y_test.npy
      - ./data/trained
    params:
      - evaluate.evaluation_model_filename
    metrics:
      - ./data/evaluated/score.json:
          cache: false
