version: "3"

services:
  prep:
    container_name: prep
    build:
      context: .
      dockerfile: Dockerfile.prep
    environment:
      - PLATFORM=docker_compose
      - API_ADDRESS=pred
    ports:
      - "8000:8000"
    command: ./run.sh
    depends_on:
      - pred

  pred:
    container_name: pred
    build:
      context: .
      dockerfile: Dockerfile.pred
    environment:
      - HTTP_PORT=8001
      - GRPC_PORT=50051
    ports:
      - "8001:8001"
      - "50051:50051"
    entrypoint: ["./onnx_runtime_server_entrypoint.sh"]
